config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :advertisements do
    member do
      patch 'add'
      patch 'cancel'
      patch 'approve'
      patch 'publish'
      patch 'archive'
    end
  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :destroy, Advertisement
      can :cancel, Advertisement.where(state: 1 || 3)
      can :approve, Advertisement.where(state: 1)
      can :publish, Advertisement.where(state: 3)
      can :archive, Advertisement.where(state: 4)
    else
      can :create, Advertisement
      can :update, Advertisement.where(state: 0)
      can :destroy, Advertisement.where(state: 1)
      can :add, Advertisement.where(state: 0)
    end
  end
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  validates :name, presence: true, length: { maximum: 256 }
  has_rich_text :body
  enum state: { draft: 0, added: 1, canceled: 2, approved: 3, published: 4, archived: 5 }

  belongs_to :user
  paginates_per 5
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, length: { maximum: 256 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { user: 0, admin: 1 }

  has_many :advertisements, dependent: :destroy
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy,
                                           :add, :cancel, :approve, :publish, :archive]

  def new
    @advertisement = Advertisement.new
  end

  def index
    @advertisements = if current_user.admin?
                        Advertisement.all
                      else
                        Advertisement.all.where(user: current_user).sort_by(&:id)
                      end
  end

  def show
  end

  def edit
  end

  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user_id = current_user.id
    if @advertisement.save
      redirect_to advertisements_path,
                  notice: 'Advertisement was successfully created as draft.'
    else
      render 'new'
    end
  end

  def update
    if @advertisement.update(advertisement_params.except(:advertisement_id))
      redirect_to advertisements_path,
                  notice: 'Advertisement was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @advertisement.destroy
    redirect_to advertisements_path,
                notice: 'Advertisement was successfully destroyed.'
  end

  def add
    @advertisement.update(state: 1)
    redirect_to advertisements_path,
                notice: 'Advertisement was successfully added.'
  end

  def cancel
    @advertisement.update(state: 2)
    redirect_to advertisements_path,
                notice: 'Advertisement was successfully canceled.'
  end

  def approve
    @advertisement.update(state: 3)
    redirect_to advertisements_path,
                notice: 'Advertisement was successfully approved.'
  end

  def publish
    @advertisement.update(state: 4)
    redirect_to advertisements_path,
                notice: 'Advertisement was successfully published.'
  end

  def archive
    @advertisement.update(state: 'draft')
    redirect_to advertisements_path,
                notice: 'Advertisement was successfully archived.'
  end

  private

  def set_advertisement
    @advertisement = Advertisement.find(params[:id])
  end

  def advertisement_params
    params.require(:advertisement).permit(:name, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @advertisements = Advertisement.published.page(params[:page])
    render home: 'index'
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/advertisements/_form.html.erb
<div class="row-fluid">
  <div class="span4 well">
    <%= simple_form_for @advertisement do |a| %>
      <fieldset>
        <legend>Advertisement</legend>
          <div class="field">
            <div class ="field">
            <strong>Title:</strong>
            </div>
            <%= a.text_field :name, :class => "input-xlarge" %>
          </div>
        <br>
          <div class="field">
            <%= a.label :body %>
            <%= a.rich_text_area :body %>
          </div>
        <br>
          <div class="form-actions">
            <%= a.submit :class => "btn btn-primary" %>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>

app/views/advertisements/edit.html.erb
<h1>Editing Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<br>
<a href="/advertisements" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Back</a>

app/views/advertisements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advertisements</h1>
<div class="span4 well">
<table class = 'table'>
  <thead>
  <tr>
    <th scope="col">Id</th>
    <th scope="col">Title</th>
    <th scope="col">Status</th>
    <th scope="col">Actions</th>
  </tr>
</thead>
  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>

        <td><%= advertisement.id %></td>
        <td><%= advertisement.name %></td>
        <td><%= advertisement.state %></td>

        <td><%= link_to 'Show', advertisement %></td>
        <td><% if can? :update, advertisement %>
          <%= link_to 'Edit', edit_advertisement_path(advertisement) %>
         <% end %>
        </td>

        <td><%if can? :add, advertisement %>
          <%if advertisement.draft? %>
           <%= link_to 'Add', add_advertisement_path(advertisement),
           method: :patch %>
          <% end %>
         <% end %>
        </td>

        <td><%if can? :approve, advertisement %>
          <%if advertisement.added? %>
           <%= link_to 'Approve' , approve_advertisement_path(advertisement),
           method: :patch %>
          <% end %>
         <% end %>
        </td>

        <td><%if can? :cancel, advertisement %>
          <%if advertisement.added? || advertisement.approved? %>
           <%= link_to 'Cancel' , cancel_advertisement_path(advertisement),
           method: :patch %>
           <% end %>
         <% end %>
        </td>

        <td><%if can? :publish, advertisement %>
          <% if advertisement.approved? %>
           <%= link_to 'Pablish', publish_advertisement_path(advertisement),
          method: :patch %>
          <% end %>
         <% end %>
        </td>

        <td><%if can? :archive, advertisement %>
          <% if advertisement.published? %>
            <%= link_to 'Archive', archive_advertisement_path(advertisement),
            method: :patch %>
          <% end %>
         <% end %>
        </td>

        <td><% if can? :destroy, advertisement %>
          <%= link_to 'Destroy', advertisement,
          method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
       </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
 <div><%if current_user.user? %>
   <%= link_to 'New Advertisement', new_advertisement_path,
   class: 'btn btn-primary btn-lg active' %>
      <% end %>
 </div>

app/views/advertisements/new.html.erb
<%= render 'form', advertisement: @advertisement %>

<br>
<a href="/advertisements" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Back</a>

app/views/advertisements/show.html.erb
<p id="notice"><%= notice %></p>

<div class="span4 well">
<p>
  <strong>Title:</strong>
  <%= @advertisement.name %>
</p>

<div class="conteiner">
  <%= @advertisement.body %>
</div>
</div>

<br>
  <% if can? :update, @advertisement %>
  <a><%= link_to 'Edit', edit_advertisement_path(@advertisement), class: 'btn btn-primary btn-lg active' %></a>
  <% end %>
<a href="/advertisements" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Back</a>

app/views/home/_header.html.erb
<nav class="navbar fixed-bottom navbar-light bg-light" style="background-color: #70AB8F">
  <form class="container">
      <a class="navbar-brand" href="/"
      style="color: black; font-size: xx-large;">Advertisements</a>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav mr-auto">
    <% if user_signed_in? %>
    <Li style="color: black; font-size: large;  padding: 12px;"><%= t '.logged' %> <strong><%= current_user.email %> </strong></Li>
      <li class='nav-item' ><%= link_to "Edit profile", edit_user_registration_path %></li>
      <li class='nav-item' ><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
       <li class='nav-item'><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
  </ul>
</div>
  </form>
</nav>

app/views/home/index.html.erb
<div>
 <%= link_to 'Create advertisement', advertisements_path,
  class: 'btn btn-primary btn-lg active' %>
</div>
<br>
<div class="row-fluid">
    <% @advertisements.each do |a| %>
        <fieldset>
          <div class="span4 well">
           <div class= "field">
             <strong><%= a.name %></strong>
           </div>
           <br>
           <div class="field">
            <%= a.body %>
           </div>
          </div>
        </fieldset>
    <% end %>
    <%= paginate @advertisements %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>